org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=/Users/mahfuzahmed/Library/Java/JavaVirtualMachines/openjdk-22.0.2/Contents/Home
android.useAndroidX=true
android.defaults.buildfeatures.buildconfig=true
flutter.compileSdkVersion=36
# Lower minSdk to support Chinese PTT devices running Android 5.1 (API 22)
flutter.minSdkVersion=22
